server:
  port: 8080

ai:
  compatibility: OPENAI

  base-url: http://localhost:11434
  path: /v1/chat/completions
  model: qwen3:8b
  api-key: ${AI_API_KEY:}
  auth-scheme: Bearer
  think:
    enabled: true               # enable optional thinking mode
#    level: medium               # optional: send low/medium/high when the upstream supports it
  tools:
    max-loops: 2
  memory:
    max-messages: 12
  client:
    timeout-ms: 180000           # wait longer for upstream completion calls
    stream-timeout-ms: 240000    # longer window for streaming responses
    retry:
      max-attempts: 3
      backoff-ms: 500

spring:
  main:
    web-application-type: reactive
  http:
    codecs:
      max-in-memory-size: 16MB

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    com.example: DEBUG
