server:
  port: 8080

ai:
  compatibility: OPENAI

  base-url: http://localhost:11434
  path: /v1/chat/completions
  model: qwen3:8b
  api-key: ${AI_API_KEY:}
  auth-scheme: Bearer
  think:
    enabled: true               # enable optional thinking mode
#    level: medium               # optional: send low/medium/high when the upstream supports it

spring:
  main:
    web-application-type: reactive
  http:
    codecs:
      max-in-memory-size: 16MB

springdoc:
  swagger-ui:
    path: /swagger-ui
