server:
  port: 8080

ai:
  compatibility: OLLAMA

  base-url: http://localhost:11434
  path: /api/chat
  model: qwen3:8b

  api-key: ${AI_API_KEY:}
  auth-scheme: Bearer

spring:
  main:
    web-application-type: reactive
  http:
    codecs:
      max-in-memory-size: 16MB

springdoc:
  swagger-ui:
    path: /swagger-ui